
year=[2018,2019,2020]

district_list=['BAGALKOTE', 'BANGALORE RURAL', 'BANGALORE URBAN', 'BELGAUM', 'BELLARY', 'BIDAR', 'BIJAPUR', 'CHAMRAJNAGAR', 'CHIKKABALLAPUR', 'CHIKMAGALUR', 'CHITRADURGA', 'DAKSHINA KANNADA', 'DAVANAGERE', 'DHARWAD', 'GADAG', 'GULBARGA', 'HASSAN', 'HAVERI', 'KODAGU', 'KOLAR', 'KOPPAL', 'MANDYA', 'MYSORE', 'RAICHUR', 'RAMANAGAR', 'SHIVAMOGGA', 'TUMKUR', 'UDUPI', 'UTTARA KANNADA', 'YADGIR']